network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      addresses:
        - 192.168.1.2/24
      nameservers:
        addresses: [192.168.1.1, 1.1.1.1]
      routes: 
        - to: default
          via: 192.168.1.1

# https://github.com/canonical/netplan/tree/main/examples
